//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 11:19:23 AM PDT 
//


package com.shippingapis.usps;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Address">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Address2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Zip5" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="Zip4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="USERID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "address"
})
@XmlRootElement(name = "AddressValidateRequest")
public class AddressValidateRequest {

    @XmlAttribute(name = "USERID")
    protected String userid;

    @XmlElement(name = "Address", required = true)
    protected AddressValidateRequest.Address address;
    

    /**
     * Gets the value of the userid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERID() {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERID(String value) {
        this.userid = value;
    }
    
    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressValidateResponse.Address }
     *     
     */
    public AddressValidateRequest.Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressValidateResponse.Address }
     *     
     */
    public void setAddress(AddressValidateRequest.Address value) {
        this.address = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Address2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Zip5" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="Zip4" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "address1",
            "address2",
            "city",
            "state",
            "zip5",
            "zip4"
    })
    public static class Address {

    	 @XmlElement(name = "Address1", required = false)
         protected String address1;
         @XmlElement(name = "Address2", required = false)
         protected String address2;
         @XmlElement(name = "City", required = false)
         protected String city;
         @XmlElement(name = "State", required = false)
         protected String state;
         @XmlElement(name = "Zip5")
         protected String zip5;
         @XmlElement(name = "Zip4")
         protected String zip4;
         @XmlAttribute(name = "ID")
         protected Byte id;

         /**
          * Gets the value of the address1 property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getAddress1() {
             return address1;
         }

         /**
          * Sets the value of the address1 property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setAddress1(String value) {
             this.address1 = value;
         }

         /**
          * Gets the value of the address2 property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getAddress2() {
             return address2;
         }

         /**
          * Sets the value of the address2 property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setAddress2(String value) {
             this.address2 = value;
         }

         /**
          * Gets the value of the city property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getCity() {
             return city;
         }

         /**
          * Sets the value of the city property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setCity(String value) {
             this.city = value;
         }

         /**
          * Gets the value of the state property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getState() {
             return state;
         }

         /**
          * Sets the value of the state property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setState(String value) {
             this.state = value;
         }

         /**
          * Gets the value of the zip5 property.
          * 
          */
         public String getZip5() {
             return zip5;
         }

         /**
          * Sets the value of the zip5 property.
          * 
          */
         public void setZip5(String value) {
             this.zip5 = value;
         }

         /**
          * Gets the value of the zip4 property.
          * 
          */
         public String getZip4() {
             return zip4;
         }

         /**
          * Sets the value of the zip4 property.
          * 
          */
         public void setZip4(String value) {
             this.zip4 = value;
         }

         /**
          * Gets the value of the id property.
          * 
          * @return
          *     possible object is
          *     {@link Byte }
          *     
          */
         public Byte getID() {
             return id;
         }

         /**
          * Sets the value of the id property.
          * 
          * @param value
          *     allowed object is
          *     {@link Byte }
          *     
          */
         public void setID(Byte value) {
             this.id = value;
         }

    }

}
