//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 11:19:23 AM PDT 
//


package com.shippingapis.usps;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.shippingapis.usps package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AddressValidateRequestAddress_QNAME = new QName("", "Address");
    private final static QName _AddressValidateRequestAddressZip4_QNAME = new QName("", "Zip4");
    private final static QName _AddressValidateRequestAddressState_QNAME = new QName("", "State");
    private final static QName _AddressValidateRequestAddressAddress2_QNAME = new QName("", "Address2");
    private final static QName _AddressValidateRequestAddressAddress1_QNAME = new QName("", "Address1");
    private final static QName _AddressValidateRequestAddressZip5_QNAME = new QName("", "Zip5");
    private final static QName _AddressValidateRequestAddressCity_QNAME = new QName("", "City");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.shippingapis.usps
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddressValidateRequest }
     * 
     */
    public AddressValidateRequest createAddressValidateRequest() {
        return new AddressValidateRequest();
    }

    /**
     * Create an instance of {@link AddressValidateResponse.Address }
     * 
     */
    public AddressValidateResponse.Address createAddressValidateResponseAddress() {
        return new AddressValidateResponse.Address();
    }

    /**
     * Create an instance of {@link AddressValidateRequest.Address }
     * 
     */
    public AddressValidateRequest.Address createAddressValidateRequestAddress() {
        return new AddressValidateRequest.Address();
    }

    /**
     * Create an instance of {@link AddressValidateResponse }
     * 
     */
    public AddressValidateResponse createAddressValidateResponse() {
        return new AddressValidateResponse();
    }

    /**
     * Create an instance of {@link AddressValidateResponse.Address.Error }
     * 
     */
    public AddressValidateResponse.Address.Error createAddressValidateResponseAddressError() {
        return new AddressValidateResponse.Address.Error();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressValidateRequest.Address }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Address", scope = AddressValidateRequest.class)
    public JAXBElement<AddressValidateRequest.Address> createAddressValidateRequestAddress(AddressValidateRequest.Address value) {
        return new JAXBElement<AddressValidateRequest.Address>(_AddressValidateRequestAddress_QNAME, AddressValidateRequest.Address.class, AddressValidateRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Zip4", scope = AddressValidateRequest.Address.class)
    public JAXBElement<String> createAddressValidateRequestAddressZip4(String value) {
        return new JAXBElement<String>(_AddressValidateRequestAddressZip4_QNAME, String.class, AddressValidateRequest.Address.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "State", scope = AddressValidateRequest.Address.class)
    public JAXBElement<String> createAddressValidateRequestAddressState(String value) {
        return new JAXBElement<String>(_AddressValidateRequestAddressState_QNAME, String.class, AddressValidateRequest.Address.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Address2", scope = AddressValidateRequest.Address.class)
    public JAXBElement<String> createAddressValidateRequestAddressAddress2(String value) {
        return new JAXBElement<String>(_AddressValidateRequestAddressAddress2_QNAME, String.class, AddressValidateRequest.Address.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Address1", scope = AddressValidateRequest.Address.class)
    public JAXBElement<String> createAddressValidateRequestAddressAddress1(String value) {
        return new JAXBElement<String>(_AddressValidateRequestAddressAddress1_QNAME, String.class, AddressValidateRequest.Address.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Zip5", scope = AddressValidateRequest.Address.class)
    public JAXBElement<Short> createAddressValidateRequestAddressZip5(Short value) {
        return new JAXBElement<Short>(_AddressValidateRequestAddressZip5_QNAME, Short.class, AddressValidateRequest.Address.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "City", scope = AddressValidateRequest.Address.class)
    public JAXBElement<String> createAddressValidateRequestAddressCity(String value) {
        return new JAXBElement<String>(_AddressValidateRequestAddressCity_QNAME, String.class, AddressValidateRequest.Address.class, value);
    }

}
