GRANT USAGE ON *.* TO 'batch'@'%' IDENTIFIED BY PASSWORD '';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`BATCH_STEP_EXECUTION_SEQ` TO 'batch'@'%';
GRANT SELECT ON `hootit`.`ListingHasDigitalContent` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`EffectiveVoucherStatuses` TO 'batch'@'%';
GRANT SELECT ON `hootit`.`UserConnection` TO 'batch'@'%';
GRANT SELECT ON `hootit`.`Roles` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`BATCH_JOB_EXECUTION` TO 'batch'@'%';
GRANT SELECT ON `hootit`.`TermsOfServices` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`BATCH_JOB_SEQ` TO 'batch'@'%';
GRANT SELECT ON `hootit`.`SellerTweetRateLimits` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`Messages` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`Listings` TO 'batch'@'%';
GRANT SELECT ON `hootit`.`ListingReplies` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`BATCH_STEP_EXECUTION` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`MessageStateChanges` TO 'batch'@'%';
GRANT SELECT ON `hootit`.`CurrentTwitterStreamSellers` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`BATCH_STEP_EXECUTION_CONTEXT` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`PaypalStatusUpdates` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`ListingStateChanges` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`BATCH_JOB_EXECUTION_PARAMS` TO 'batch'@'%';
GRANT SELECT ON `hootit`.`CurrentPreapprovals` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`MetricsJobExecutions` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`Payments` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`ReplyPagingStatuses` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`Inventories` TO 'batch'@'%';
GRANT SELECT, INSERT ON `hootit`.`Users` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`BusinessMetrics` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`Vouchers` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`Addresses` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`SentOutboundCommunications` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`BATCH_JOB_EXECUTION_CONTEXT` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`EffectivePaymentStatuses` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`BATCH_JOB_EXECUTION_SEQ` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`Preapprovals` TO 'batch'@'%';
GRANT SELECT ON `hootit`.`FacebookUpdateNotifications` TO 'batch'@'%';
GRANT SELECT, UPDATE ON `hootit`.`VOUCHER_SEQ` TO 'batch'@'%';
GRANT SELECT ON `hootit`.`DownloadInstances` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE ON `hootit`.`BATCH_JOB_INSTANCE` TO 'batch'@'%';
GRANT SELECT ON `hootit`.`CurrentPaymentStatus` TO 'batch'@'%';
GRANT SELECT ON `hootit`.`ContentFiles` TO 'batch'@'%';
GRANT EXECUTE ON PROCEDURE `hootit`.`getnextsequencevalue` TO 'batch'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO 'hootit'@'%' IDENTIFIED BY PASSWORD '' WITH GRANT OPTION;
GRANT REPLICATION SLAVE ON *.* TO 'rdsrepladmin'@'%' IDENTIFIED BY PASSWORD '';
GRANT USAGE ON *.* TO 'stream'@'%' IDENTIFIED BY PASSWORD '';
GRANT SELECT, INSERT, DELETE ON `hootit`.`CurrentTwitterStreamSellers` TO 'stream'@'%';
GRANT SELECT, INSERT ON `hootit`.`Messages` TO 'stream'@'%';
GRANT SELECT ON `hootit`.`UserConnection` TO 'stream'@'%';
GRANT SELECT ON `hootit`.`Users` TO 'stream'@'%';
GRANT SELECT ON `hootit`.`Listings` TO 'stream'@'%';
GRANT SELECT ON `hootit`.`Users_Roles` TO 'stream'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'rdsadmin'@'localhost' IDENTIFIED BY PASSWORD '' WITH GRANT OPTION;
